[tool.poetry]
name = "customer-service-workflow"
version = "0.1.0"
description = ""
authors = ["Ammielle WB <61096548+ammiellewb@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
dependencies = [
    "swarmzero (>=0.0.3,<0.0.4)"
]
python-dotenv = "^1.1.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
